[workspace]
channels = ["conda-forge"]
name = "BRACE Bed Rest"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
r-readxl = ">=1.5.0,<2"
r-lmertest = ">=3.2_1,<4"
r-base = ">=4.5.3,<4.6"
r-tidyverse = ">=2.0.0,<3"
r-emmeans = ">=2.0.4,<3"
r-writexl = ">=1.5.4,<2"
r-lme4 = ">=2.0_6,<3"
